// test-frontend/src/App.vue
<template>
  <div id="app">
    <Header></Header>
    <Main></Main>
  </div>
</template>

<script>
import Header from './components/Header.vue'
import Main from './components/Main.vue'

export default {
  name: 'app',
  components: {
    Header, Main
  },
  data() {
      return {

      }
  },
}
</script>

<style lang="scss">
    @import "assets/scss/app.scss";
</style>

// app/App.tsx
import React from 'react';

import './App.scss';
import Header from './components/header';
import Gallery from './components/gallery';

function App() {
  return (
    <div className="App">
      <Header />
      <div className="container">
        <Gallery />
      </div>
    </div>
  );
}

export default App;
